Actions: clarify that it runs tests
nrfconnect/ncs-example-application pull request #12
Opened 2024-03-19 20:31 UTC by coderbyheart

The GitHub Actions workflow does not build the application. Therefore the workflow file is renamed and the first test step is renamed.

2024-03-19 21:47 UTC, gmarull requested changes
Twister is used to build the application in potential multiple configurations. If this needs better clarification please submit a PR or issue upstream.

2024-03-19 22:58 UTC, coderbyheart commented
Sorry, I don't follow.

> Twister is used to build the application in potential multiple configurations.

But in the workflow file in this repo this step that is called `build` does not actually build it. It runs the tests.

https://github.com/nrfconnect/ncs-example-application/pull/12/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fL27

> If this needs better clarification please submit a PR or issue upstream.

Which file is the workflow based on that should receive that PR?

2024-03-20 06:49 UTC, balaji-nordic requested changes

2024-03-20 06:49 UTC, balaji-nordic commented on .github/workflows/tests.yml
> +name: Tests
```suggestion
name: Build and test
```

2024-03-20 06:49 UTC, balaji-nordic commented on .github/workflows/tests.yml
> +  tests:
The job also builds some configurations without running any tests (i.e the non-emulated platforms). It only runs a few tests. So this job's name can remain `build` or be changed to `build_and_test`, to be more correct.

2024-03-20 06:49 UTC, balaji-nordic commented on .github/workflows/tests.yml
> +      - name: Twister Tests (app)
```suggestion
      - name: Build application
```
As this task is purely a build. No tests are run. Not even on simulated environment

2024-03-20 07:42 UTC, closed without merging

2024-03-20 07:48 UTC, coderbyheart commented
I see now that "build" in Twister context means something different than what I understand. I expected the build step to produce a firmware file that can be flashed.

2024-03-20 08:35 UTC, gmarull commented
> I see now that "build" in Twister context means something different than what I understand. I expected the build step to produce a firmware file that can be flashed.

it should actually be available in one of the twister output folders