Update example documentation
nrfconnect/ncs-example-application pull request #23
Opened 2024-09-25 10:44 UTC by wiba-nordic

Updates the Example Application's document to use
the sphinx-ncs-theme v0.7.4, which was the latest version I could get to easily work.

Also adds some example pages and documentation guidance.

2024-09-25 10:49 UTC, wiba-nordic commented
No idea idea how to fix the build error. The documentation builds locally.

2024-09-25 10:53 UTC, gmarull requested changes
most changes seem unnecessary, also, we should not recommend any theme, this is for custom applications, why will they want Nordic logo?

2024-09-25 11:41 UTC, wbober commented
> most changes seem unnecessary, also, we should not recommend any theme, this is for custom applications, why will they want Nordic logo?

Nordic theme is useful for Nordic teams that move their products to add-ons. I would like it to be available. Can we make it, so it is one of the available options (default or Nordic)?

2024-09-25 11:48 UTC, wiba-nordic commented
In addition to what Wojciech said, the Example Application is still a Nordic offering, so it is good for it to have Nordic styling and quality. I do agree that it would probably be good to document how to change it, in which case we can leave the Alabaster theme as a commented-out option in the file.

The changed content is likewise good for any Nordic projects, and makes it easier for outside contributors to create documentation that is at least somewhat consistent with Nordic documentation. This, in turn, is good for end users when the add-ons are consistently documented.

2024-09-25 11:50 UTC, gmarull commented
Note: Nordic theme is no longer maintained, as we've moved to Zoomin. So at some point it will likely break.

2024-09-25 11:55 UTC, wiba-nordic commented
How much of the theme is the CSS (which shouldn't break), and how much is Breathe functionality?

2024-09-25 12:47 UTC, gmarull commented
> How much of the theme is the CSS (which shouldn't break), and how much is Breathe/Sphinx functionality?

It depends on rtd theme, and has quite a few tweaks on top, like supporting tabs. I'd not recommend it for external usage.

2025-10-16 12:05 UTC, carlescufi commented
Closing this for now

2025-10-16 12:05 UTC, closed without merging